name: validate
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-macos:
    runs-on: [self-hosted, macos]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: |
          cp ../../../sm64-baserom.us.z64 baserom.us.z64
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Debug
          cmake --build build-cmake --config Debug --target ExtractAssets
          cmake --build build-cmake --config Debug
      
